# docker-compose.yml

version: "3.9"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_go
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASS: root
      DB_NAME: crud_go
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
